language: node_js
node_js:
  - "8"

branches:
  only:
  - master

cache:
  directories:
    - "node_modules"
    # - $HOME/.cache/pip

before_install:
  - npm install -g npm@latest
  - npm install -g hexo-cli@latest
  - pip install --user awscli 

install:
  - npm install

before_script:
  - sed -i "s/<GOOGLE_ANALYTICS_ID>/${GOOGLE_ANALYTICS_ID}/" _config.release.yml
  - sed -i "s/<FBSDK_APP_ID>/${FBSDK_APP_ID}/" _config.release.yml
  - sed -i "s/<FBSDK_ADMIN_ID>/${FBSDK_ADMIN_ID}/" _config.release.yml

script:
  - webpack -p
  - hexo clean
  - hexo generate --config _config.yml,_config.links.yml,_config.release.yml

before_deploy:
  - aws configure set aws_access_key_id $AWS_KEY
  - aws configure set aws_secret_access_key  $AWS_SECRET
  - aws configure set region $AWS_S3_REGION
  - aws configure set preview.cloudsearch true
  # - aws s3 rm s3://$AWS_S3_BUKET --recursive

deploy:
  provider: s3
  access_key_id: $AWS_KEY
  secret_access_key: $AWS_SECRET
  region: $AWS_S3_REGION
  bucket: $AWS_S3_BUKET
  skip_cleanup: true
  cache_control: "max-age=86400"
  local_dir: public
  acl: public_read

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution-id $AWS_CF_DISTRIBUTION_ID --paths "/*"